/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./boardWithPieces.gltf --transform 
Files: ./boardWithPieces.gltf [4.99MB] > boardWithPieces-transformed.glb [860.53KB] (83%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boardWithPieces-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.656, -0.003]} rotation={[Math.PI / 2, 0, 0]} scale={0.015}>
        <mesh geometry={nodes['TTT-field-circle_1'].geometry} material={materials.Ply_sides} />
        <mesh geometry={nodes['TTT-field-circle_2'].geometry} material={materials.Ply_top} />
        <mesh geometry={nodes['TTT-field-circle_3'].geometry} material={materials.Ply_sticks} />
        <mesh geometry={nodes['TTT-field-circle_4'].geometry} material={materials.Ply_edges} />
      </group>
      <mesh geometry={nodes['TTT-piece-circle'].geometry} material={materials.Light} position={[-0.471, 0.426, 0.466]} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh geometry={nodes['TTT-piece-circle001'].geometry} material={materials['Dark.001']} position={[0.469, 0.426, -0.472]} rotation={[Math.PI / 2, 0, 0]} scale={0.015} />
    </group>
  )
}

useGLTF.preload('/boardWithPieces-transformed.glb')
