import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React, { useCallback } from "react";
import * as THREE from 'three';
import { CameraControls, Center, PerspectiveCamera, Stage, Stars, Text3D, useFont, Environment, useGLTF, useHelper, SoftShadows, MeshTransmissionMaterial, BakeShadows } from '@react-three/drei'

import { api } from "~/utils/api";
import { Canvas } from '@react-three/fiber'
import { BoardWithPieces } from "~/components/BoardWithPieces";
import { BoardSelections } from "~/components/BoardSelections";
import { Piece } from "~/components/Piece";
import { getNextPieceHeight } from "~/utils/getNextPieceHeight";
import { CSpotLight, CAmbientLight } from "~/components/Lights";
// import { PieceInstance } from "~/components/Pieces/PieceInstance";
import { EGameState, TGameData, EPlayer, ESquareState } from "~/utils/gameTypes";
import { checkIsWin } from "~/utils/checkIsWin";

const SETTINGS = {
  SHADOW_QUALITY: 1 // 0 - off, 1 - on, 2 - soft shadows, 3 - high quality soft shadows
}

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen bg-gradient-to-b from-yellow-500 to-orange-900">
        <div className="w-screen h-screen">
          <Scene/>
        </div>
      </main>
    </>
  );
}

const Scene: React.FC = () => {
  const [gameData, setGameData] = React.useState<TGameData>({
    state: EGameState.Playing,
    turn: EPlayer.Light,
    board: new Array(4).fill(new Array(4).fill(new Array(4).fill(ESquareState.Empty)))
  });

  const addPiece = (positionVector: THREE.Vector2) => {
    setGameData((prevState) => {
      if (gameData.state !== EGameState.Playing) return prevState;
      const newState = JSON.parse(JSON.stringify(prevState));
      const pieceHeight = getNextPieceHeight(newState, positionVector.x, positionVector.y);
      if (pieceHeight > 3) return prevState;
      newState.board[positionVector.x][positionVector.y][pieceHeight] = prevState.turn == EPlayer.Light ? ESquareState.Light : ESquareState.Dark;
      if (newState.turn == EPlayer.Light) {
        newState.turn = EPlayer.Dark;
      } else {
        newState.turn = EPlayer.Light;
      }

      const isWin = checkIsWin(newState);
      if (isWin) {
        console.log("There is a win");
        newState.state = isWin;
      }

      return newState;
    });
  }
  console.log("gameData", gameData);

  const setLightWin = () => {
    setGameData((prevState) => {
      const newState = JSON.parse(JSON.stringify(prevState));
      newState.state = EGameState.LightWin;
      return newState;
    });
  }

  const setDarkWin = () => {
    setGameData((prevState) => {
      const newState = JSON.parse(JSON.stringify(prevState));
      newState.state = EGameState.DarkWin;
      return newState;
    });
  }

  return (
    <Canvas shadows>
      <CSpotLight 
        id={1}
        position={{
          x: 3,
          y: 6,
          z: 3,
        }}
        visible={true}
        color={"#FFDDB5"}
        intensity={100}
        castShadow={true}
      />
      <CSpotLight
        id={2}
        position={{
          x: -3,
          y: 6,
          z: 3,
        }}
        visible={true}
        color={"#FFDDB5"}
        intensity={100}
        castShadow={true}
      />
      <CAmbientLight
        color={"#FFDDB5"}
        intensity={0.5}
      />

      {/* <PerspectiveCamera
        makeDefault
        position={[0, 0.8, 5]}
        fov={75}
        aspect={2}
        near={0.1}
        far={1000}
      /> */}
      <CameraControls/>
      <React.Suspense fallback={null}>
        <BoardWithPieces/>
        {
          gameData.board.map((row, i) => {
            return row.map((col, j) => {
              return col.map((square, k) => {
                if (square == ESquareState.Empty) return (<></>);
                return <Piece pos={new THREE.Vector3(i, j, k)} isDark={
                  gameData.state != EGameState.LightWin 
                  && (
                    gameData.state == EGameState.DarkWin
                    || square == ESquareState.Dark
                  )
                }/>
              });
            })
          })
        }
        {
          SETTINGS.SHADOW_QUALITY > 1 && (<SoftShadows size={60} samples={8} focus={0.5}/>)
        }
        {/* <BakeShadows /> */}
        <BoardSelections addPiece={addPiece}/>
      </React.Suspense>
    </Canvas>
  )
}

